###########
# Imports #
###########

import cv2

#############
# Constants #
#############

# <-- FEATURE EXTRACTOR --> #
DEFAULT_FEATURE_EXTRACTOR = cv2.xfeatures2d.SURF_create(extended=True)

# <-- MATCHER --> #
DEFAULT_MATCHER_INDEX_PARAMS = {'M': 15, 'indexThreadQty': 8, 'efConstruction': 100, 'post': 0}
DEFAULT_MATCHER_QUERY_PARAMS = {'efSearch': 100}

# <-- CLASSIFIER --> #
DEFAULT_CLASSIFER_IMAGE_SIZE = 256
DEFAULT_CLASSIFIER_KEYPOINT_STRIDE = 8
DEFAULT_CLASSIFIER_KEYPOINT_SIZES = [12, 24, 32, 48]
DEFAULT_CLASSIFIER_MATCHER_PATH = "./matchers/classifier.hnsw"
DEFAULT_CLASSIFIER_FORCE_MATCHER_COMPUTE = False
DEFAULT_CLASSIFIER_K_NN = 1
DEFAULT_CLASSIFIER_SCORE_SIGMA = 0.2

# <-- DETECTOR --> #
DEFAULT_DETECTOR_CATALOG_IMAGE_WIDTHS = [800, 600, 400, 300, 200, 100]
DEFAULT_DETECTOR_QUERY_IMAGE_WIDTH = 2500
DEFAULT_DETECTOR_KEYPOINT_STRIDE = 6
DEFAULT_DETECTOR_KEYPOINT_SIZES = [24]
DEFAULT_DETECTOR_MATCHER_PATH = "./matchers/detector.hnsw"
DEFAULT_DETECTOR_FORCE_MATCHER_COMPUTE = False
DEFAULT_DETECTOR_K_NN = 1
DEFAULT_DETECTOR_SCORE_SIGMA = 0.2
DEFAULT_DETECTOR_N_RANSAC = 20

# <-- OTHER --> #
CATALOG_IMAGES_PATH = "../Images/Catalog/*"
CLASSIFICATION_QUERY_IMAGES_PATH = "../Images/Query/*"
DETECTOR_QUERY_IMAGES_PATH = "../Images/Query Raw/JPEGImages/*"
BACKGROUND_LABEL = "Background"
VERBOSE = True
COLORS = [(255, 255, 255),
          (128, 128, 128),
          (128,   0, 128),
          (  0,   0, 255),
          (  0, 255, 165),
          (  0, 255, 255),
          (133, 199,  21),
          (211, 148,   0),
          (154,   0, 250),
          (250, 135, 206),
          (158, 205, 183)]